apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: 058264091271.dkr.ecr.eu-north-1.amazonaws.com/payments:latest
        name: payments
        env: 
          - name: PORT
            value: "3001"
          - name: NOTIFICATIONS_HOST
            value: notifications
          - name: NOTIFICATIONS_TCP_PORT
            value: "3000"
          - name: TEST_CUSTOMER_ID
            value: cus_QNjTQZknqU0YTL
          - name: STRIPE_PUBLIC_KEY
            value: pk_test_51PSL5vDsBQSiSo68D9Xhdlveoektmr6egiddQ02OVS3TxsiXj1JBGfMmMpPZMJR13sz7Kv4JjXrkszERfrAUfrXj006FV2lgVn
          - name: STRIPE_SECRET_KEY
            valueFrom:
               secretKeyRef:
                name: stripe
                key: apiKey
        ports: 
        - containerPort: 3001
   
